#!/bin/sh

# HOWTO: ADD THE SCRIPT TO CRON
# 1. cp the script somewhere
# 2. append "0 4 * * 1 path" to crontab
#
# This script does this if given cron as first argument

if [  $(id -u) -ne 0 ]; then
	echo "This script must be ran as root!"
	exit 1
fi

if [ "$1" = "cron" ]; then
	cp -p "$0" /usr/local/bin/updpkgs.sh
	echo "0 4 * * 1 /usr/local/bin/updpkgs.sh" >> /etc/crontab
	echo "con job added!"
	exit 0
fi

logf=/var/log/update_script.log
echo "Updating, $(date)" > $logf
apt-get update >> $logf 2>&1
apt-get upgrade -y >> $logf 2>&1
