#!/bin/sh

# HOWTO: ADD THE SCRIPT TO CRON
# 1. cp the script somewhere
# 2. append "0 0 * * * root path" to crontab
#
# This script does this if given cron as first argument

if [  $(id -u) -ne 0 ]; then
	echo "This script must be ran as root!"
	exit 1
fi

if [ "$1" = "cron" ]; then
	cp -p "$0" /usr/local/bin/chkcrontab.sh
	echo "0 0 * * * root /usr/local/bin/chkcrontab.sh" >> /etc/crontab
	echo "con job added!"
	exit 0
fi

md5file="/var/log/crontab_md5.txt"
md5tmp="/tmp/crontab_md5_tmp.txt"
filetc="/etc/crontab"

[ ! -f "$md5file" ] && md5sum "$filetc" > "$md5file"
md5sum "$filetc" > "$md5tmp"

if [ ! -z "$(diff "$md5file" "$md5tmp")" ]; then
	echo "$filetc has changed!" | mail -s "$filetc notification" root
	rm -f "$md5file"
	mv "$md5tmp" "$md5file"
else
	rm -f "$md5tmp"
fi
