#!/bin/sh
mode="mouli"
[ "$(whoami)" != "deepthought" ] && [ "$(uname)" = "Darwin" ] && mode="all"
RANDOM=$$
if [ "$mode" != "mouli" ] && [ $(( $RANDOM % 2 )) -eq 1 ]; then
	echo "        :::      ::::::::"
	echo "      :+:      :+:    :+:"
	echo "    +:+ +:+         +:+"
	echo "  +#+  +:+       +#+"
	echo "+#+#+#+#+#+   +#+"
	echo "     #+#    #+#"
	echo "    ###   ########"
	echo "Hurray!, ya got lucky!"
else
	echo "42"
	[ "$mode" != "mouli" ] && echo "ya ain't got lucky at all!"
fi
